### PR TITLE
#11

### PR DESCRIPTION
**Pull request by abennici**
First part of correction detailed in SMT Report of correction :
- add some additional text in Introduction, Data Consideration, Simple Dataset section
- add specific error message for CMSY, bad date format
- suggest error message for non  chronological dates but lack of stability
- add time out control fix to 10 min
- add library package R.utils need to time out control

### CODE REVIEW

**Comment by eblondel** [comment]
@abennici just a note for ``R.utils`` to remember adding it to Dockerfile, for installation when building image

**Comment by eblondel** [comment]
@pink-sh Hello Enrico, would it be possible that you merge this pull request from @abennici ? We will then ask a deployment to Shinyproxy. Thanks!

**Comment by eblondel** [comment]
@pink-sh @abennici has worked on a new version of SMT tool. would it be possible to merge it to your master and create a tag? We would like then to ask a deployment into ShinyProxy
Thank you!

**Comment by pink-sh** [comment]
merged

**Comment by eblondel** [comment]
Thanks, i've actually set another PR, because the last line of the dockerfile was broken
https://github.com/pink-sh/StockMonitoringTool/pull/10

**Pull request merged**
